"""Added new columns

Revision ID: 7b5100084ce1
Revises: 38b1cffbe004
Create Date: 2025-03-01 23:11:25.821232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5100084ce1'
down_revision: Union[str, None] = '38b1cffbe004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() :
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('about', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('description', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('website', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('email', sa.String(), nullable=False))
    op.add_column('companies', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('location', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('established', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=True)
    op.create_unique_constraint(None, 'companies', ['phone'])
    # ### end Alembic commands ###


def downgrade() :
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.drop_column('companies', 'established')
    op.drop_column('companies', 'location')
    op.drop_column('companies', 'phone')
    op.drop_column('companies', 'email')
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'description')
    op.drop_column('companies', 'about')
    # ### end Alembic commands ###
